### ISSUE TITLE
FluentUtils::formatQuery breaks INSERT values

### ISSUE THREAD

**Issue by derlhurgoyf** [envms/fluentpdo#126]
When inserting values these are directly inserted into the sql statement and not passed as parameters. Then values like "ARMANDO" or "ALEJANDRO" or any other term that contains some of the keywords mentioned in FluentUtils::formatQuery will receive a line break and four spaces and end up as

```
ARM
    ANDO
```

and

```
ALEJ
    ANDRO
```

A quick fix would be to use word limit in preg like this:

``` php
$query = preg_replace(
        '/\b(INNER|LEFT|RIGHT|CASE|WHEN|END|ELSE|AND)\n/', "\n    $0", $query
    );
```

However any phrases as values containing these keywords will still be modified. 
Better would be passing insert values as PDO parameters and only format the SQL query.

**Comment by cbornhoft** [comment]
See commit [here](https://github.com/envms/fluentpdo/commit/ae60ac0c60da8bd19188c1f5b4c51d8d3527f252) for fix
