### ISSUE TITLE
Throw meaningful exceptions

### ISSUE THREAD

**Issue by PawelDecowski** [envms/fluentpdo#142]
Currently, when I mistype a table or column name, the exception thrown is:

```
Objects returned by SelectQuery::getIterator() must be traversable or implement interface Iterator
```

This makes debugging very hard. When a query fails, the exception message should contain the error information from the database engine (eg table `user` not found; or column `email` not found).

**Comment by PaulKish** [comment]
+1

**Comment by cbornhoft** [comment]
Will take this issue into consideration on implementing `FluentException`.

**Comment by element-code** [comment]
@cbornhoft isn't `FluentPDOException` the right name?
