### ISSUE TITLE
How to get error or formed query

### ISSUE THREAD

**Issue by AlexMarlo** [envms/fluentpdo#161]
I have code like this

```
$this->_builder = new \FluentPDO( ...)
$query = $this->_builder->insertInto( $this->_table, $fields);
    if( $id = $query->execute())
    {
      ...
    }
    else
    {
      How to get mysql error here?
    }`
```

don't tell me about

`$this->_builder->getPdo()->errorInfo()`

it returns

```
array(3) {
  [0]=>
  string(5) "00000"
  [1]=>
  NULL
  [2]=>
  NULL
}

```

And project have http://fpdo.github.io/fluentpdo/ this great page, which has none information about errors.

Then i try to get query and execute it directly, to see errors, and i have this

```
INSERT INTO order (user_id, from_text, from_geo_text, from_lat, from_long, to_text, to_geo_text, to_lat, to_long, time, distance, price, done, driver_id, utime, ctime)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
```

And this is not a query, this is just some information about how query can looks like.

Why even here it can't return this:

```
$values = implode( ",", $fields);
return "INSERT INTO order (user_id, from_text, from_geo_text, from_lat, from_long, to_text, to_geo_text, to_lat, to_long, time, distance, price, done, driver_id, utime, ctime)
VALUES (".$values.")";
```

Always when i return to FluentPDO. it is pain to get normal error information or to get formed query.
Do something already!

**Comment by cbornhoft** [comment]
How you have it now should work. In your case `$this->_builder->getPdo()->errorInfo()` should return some error data if it was a query error.

If you're asking about how to handle Fluent specific errors, that's something that is not currently built out and will be developed for the 2.0 release. We can't add a proper error handler at this point without creating breaking changes to the 1.1.x releases.
