### ISSUE TITLE
Bind variables for select clause

### ISSUE THREAD

**Issue by iamogbz** [envms/fluentpdo#169]
How would you perform this pdo query with fluentpdo

query >> SELECT distance_function(geolocation, POINT(?,?)) distance  FROM locations WHERE distance_function(geolocation, POINT(?,?)) <= ?
params >> [8.7, 2.3, 8.7, 2.3, 100]

apologies if I've missed something obvious

**Comment by cbornhoft** [comment]
That's far too complex to build using a query builder. Fluent provides access to the original PDO instance, so you'd be better off calling that, and running the raw query there.
