### ISSUE TITLE
formatQuery method - incorrect formatting bug

### ISSUE THREAD

**Issue by ngagnon1** [envms/fluentpdo#170]
The method formatQuery in class FluentUtils adds a newline after one of several keywords.  This causes an issue because it does nothing to check for the context of the keywords.  This causes newlines to be inserted even if the keywords appear in a string value within the query.

I had an issue with a select query with a WHERE condition like field = 'hash string' and the hash string contained a keyword so the format function automatically added the newline which caused the select to not return a match.

**Comment by cbornhoft** [comment]
This is indeed a massive oversight. Not sure how anyone didn't have this problem before!

**Comment by pemedina** [comment]
@ngagnon1 care to share your failing select query?
I am playing with several regular expressions to find a workaround..

**Comment by cbornhoft** [comment]
Fixed in #210
