### ISSUE TITLE
PGSQL Driver does not support lastInsertId()

### ISSUE THREAD

**Issue by Maxim-Mazurok** [envms/fluentpdo#173]
Hello, I'm using PGSQL (PostgreSQL) Driver and fpdo/fluentpdo v.1.0.0 from composer.
It is very similar to the issue #164 _ODBC Driver does not support lastInsertId()_
But I know how to fix it.
Generally, there are 2 ideas:
1) By default, postgresql will create a sequence "`{{table_name}}_id_seq`", where "`{{table_name}}`" = table name. So, we've got to check for driver:
```
$fpdo->getPdo()->getAttribute(PDO::ATTR_DRIVER_NAME) === 'pgsql'
```
and get last insert id:
```
return $fpdo->getPdo()->lastInsertId($table.'_id_seq');
```
2) More universal way would be to pass this '_id_seq' string as a parameter to `execute()` function. Like so:
```
public function execute($suffix) {
	$result = parent::execute();
	if ($result) {
		if (!empty($suffix)) {
			return $this->getPDO()->lastInsertId($table.'_id_seq');
		} else {
			return $this->getPDO()->lastInsertId();
		}
	}
	return false;
}
```
[ Read more |  stackoverflow.com ](http://stackoverflow.com/a/29036598/4536543)

**Comment by StefanYohansson** [comment]
InsertQuery execute method receive a parameter sequence.

see: https://github.com/envms/fluentpdo/commit/14eada8efab2311d5427087f436b4470cde1ffc5
