### ISSUE TITLE
Regex in WHERE-clause triggers smart join

### ISSUE THREAD

**Issue by afk** [envms/fluentpdo#179]
## Reproduction:

``` php
$fpdo->from('table')
     ->select(null)
     ->select('id')
     ->where('nummer REGEXP \'[[:alpha:]]$\'')
     ->fetchAll();
```

generates

``` sql
SELECT id
FROM gebaude
    LEFT JOIN alpha ON alpha.gebaude_id = gebaude.id
WHERE nummer REGEXP '[[:alpha:]]$'
```
## Current workaround:

Using `disableSmartJoin()`

``` php
$fpdo->from('table')
     ->disableSmartJoin()
     ->select(null)
     ->select('id')
     ->where('nummer REGEXP \'[[:alpha:]]$\'')
     ->fetchAll();
```

generates

``` sql
SELECT id
FROM gebaude
WHERE nummer REGEXP '[[:alpha:]]$'
```
## Further information:

Error seems to emerge in [CommonQuery->buildQuery()](https://github.com/envms/fluentpdo/blob/master/FluentPDO/CommonQuery.php#L244-L254) where [createUndefinedJoins](https://github.com/envms/fluentpdo/blob/master/FluentPDO/CommonQuery.php#L263-L286) is [called](https://github.com/envms/fluentpdo/blob/master/FluentPDO/CommonQuery.php#L249).

**Comment by afk** [comment]
Oops. I should have read the other issues in more detail. This one propably duplicates/faces the same problem as #177.

**Comment by cbornhoft** [comment]
See issue #177
