### ISSUE TITLE
Discussion: Switch to PHPUnit for testing?

### ISSUE THREAD

**Issue by timwattenberg** [envms/fluentpdo#181]
- [PHPUnit](https://phpunit.de/) is the de facto standard for testing in PHP
- testing querys and their parameters are just string and array comparisons
- actual query execution could be tested by the build in [database testing](https://phpunit.de/manual/current/en/database.html)

Additionally benefits:
- code coverage analysis
- testing exceptions

**Comment by jkufner** [comment]
Writing tests with PHPUnit and similar tools is far more difficult than using PHPT. A huge benefit of PHPT is the simplicity. It is so easy to write tests that it is easier to develop a feature using tests than other way around.

The trick is in using the test output. To write a comparison you have to know what should be the result to compare with. When producing output for PHPT you just dump the variable and play with the code until the output is correct. Then you simply store the correct output and you are done. And when something goes wrong, you just look at output and you see the problem. With PHPUnit you get assert failed and have no idea what happened before.

To test a database queries, you need only few functions to dump query results. Nothing more.

Exceptions can be tested with PHPT very easily:

    try {
        doSomethingThatShouldFail();
        echo "Success :(\n";
    }
    catch (\Exception $ex) {
        echo "Failed as expected :)\n";
        echo $ex->getMessage(), "\n";
    }

And test coverage is about using XDebug. You don't need PHPUnit for that.

PHPT is extremely versatile and yet simple.

**Comment by cbornhoft** [comment]
PHPUnit is definitely the go-to library for unit testing and it is what we'll be using for all tests moving forward into 2.0
