### ISSUE TITLE
Add prefix

### ISSUE THREAD

**Issue by aaroniker** [envms/fluentpdo#186]
Whats the best way to add a table prefix to all the methods:

from($table)
insertInto($table)
update($table)
deleteFrom($table)

Thanks!

**Comment by cbornhoft** [comment]
This would a be a great feature to add! In the meantime, you're best bet is to extend the FluentPDO class:

    class PrefixedPDO extends FluentPDO {
    
        protected $prefix = '';
    
        public function from($table, $primaryKey = null) {
            parent::from("{$this->prefix}.{$table}", $primaryKey);
        }
    
        public function insertInto($table, $values = array()) {
            parent::insertInto("{$this->prefix}.{$table}", $values);
        }
    
        public function update($table, $set = array(), $primaryKey = null) {
            parent::update("{$this->prefix}.{$table}", $set, $primaryKey);
        }
    
        public function deleteFrom($table, $primaryKey = null) {
            parent::deleteFrom("{$this->prefix}.{$table}", $primaryKey);
        }
        
        public function setPrefix($prefix) {
            $this->prefix = $prefix;
        }
        
        public function getPrefix() {
            return $this->prefix;
        }
    
    }

Now I just wrote this up in the last 2 minutes so it's not guaranteed to work without some tweaking, but that's the idea behind it.

**Comment by aaroniker** [comment]
@cbornhoft thanks for your reply!
I need to add `return` to the `parent::` methods as well - this is what i got now:

```php
class FluentPDOPrefix extends FluentPDO {

    protected $prefix = '';

    public function from($table, $primaryKey = null) {
        return parent::from($this->prefix.$table, $primaryKey);
    }

    public function insertInto($table, $values = array()) {
        return parent::insertInto($this->prefix.$table, $values);
    }

    public function update($table, $set = array(), $primaryKey = null) {
        return parent::update($this->prefix.$table, $set, $primaryKey);
    }

    public function deleteFrom($table, $primaryKey = null) {
        return parent::deleteFrom($this->prefix.$table, $primaryKey);
    }

    public function setPrefix($prefix) {
        $this->prefix = $prefix;
    }

    public function getPrefix() {
        return $this->prefix;
    }

}
```

It's working :) Thanks!
