### ISSUE TITLE
OR clause, Like clause in where

### ISSUE THREAD

**Issue by rajnisheu** [envms/fluentpdo#188]
Hi,

Thanks for a great library.

I checked the documentation on http://envms.github.io/fluentpdo/ but am missing some guidance on building multiple OR/AND conditions with LIKE. For example
````
SELCT * FROM data WHERE (company LIKE %abc% OR fname LIKE %abc%) AND user_role > 7
````

This comes from a search form so am hoping I can use PDO to escape it with the library.

Any help appreciated!
Thanks

**Comment by elpocko** [comment]
`from('data')->where('(company LIKE ? OR fname LIKE ?) AND user_role > 7', '%abc%', '%abc%')->fetchAll();`

Documentation is lacking, but you can always check the test directory for examples.

**Comment by rajnisheu** [comment]
Thanks! I am happy to add to documentation with my solution if you could point me to a location.

Because, `where` clauses are frequently dynamic, I needed a way to build it. This is what I did:

````
...
$fpdo = new FluentPDO($pdo);

$name = 'abc';		// for the like clause
$typeFilter = 0;	// integer
$limit = 10;		// set to null if you want to get everything
$offset = null;		// null basically turns criteria off

	// the first select(null) in the following statement turns "SELECT *" off
	// the second selects the columns
$query = $fpdo->from('records')
	->select(null)
	->select(array('record_id','users.user_name'))
	->leftJoin('users ON users.user_id = records.user_id')
	->limit($limit)
	->offset($offset)
	;

if ($name) {
  $query = $query->where('(company LIKE ? OR fname LIKE ? OR lname LIKE ?)', '%'.$name.'%' , '%'.$name.'%', '%'.$name.'%'); 
  }
if ($typeFilter) {
		// additional condition will AND to previous statement if it was set
  $query = $query->where("company_type_id", $typeFilter); 
  }

$results = $query->fetchAll();
````

**Comment by elpocko** [comment]
I don't think theres a way to add to documentation.

You could simplify your code and improve readability though:    

	->select(array('record_id','users.user_name'))  
can be written as  

	->select('record_id, users.user_name')  

and  

     $query = $query->where('(company LIKE ? OR fname LIKE ? OR lname LIKE ?)', '%'.$name.'%' , '%'.$name.'%', '%'.$name.'%');  

can be written as

    $params = [':name' => "%$name%"];
    $query = $query->where('(company LIKE :name OR fname LIKE :name OR lname LIKE :name)', $params); 

Hope this helps.

**Comment by cbornhoft** [comment]
Yes, documentation is something that needs to improve greatly.
