### ISSUE TITLE
No error when calling nonexistant query methods 

### ISSUE THREAD

**Issue by elpocko** [envms/fluentpdo#189]
I had a bug in my application where data would be returned unsorted, although there was an orderBy clause in my query:

    $query = $fdpo->from('table')->oderBy('field');

It took me a long time to find the typo in my code (`oderBy` instead of `orderBy`).

The `__call` method in CommonQuery.php causes errors like these to be silently ignored.

    // this should result in some kind of error
    $fdpo->from('table')->qwertiop()->dont()->make()->typos();

**Comment by cbornhoft** [comment]
Thanks for reporting this @elpocko, much appreciated.

**Comment by cbornhoft** [comment]
Fixed in #214
