### ISSUE TITLE
Custom Query / Raw Query

### ISSUE THREAD

**Issue by novhex** [envms/fluentpdo#191]
Is there a support for Custom or Raw query in fluentPDO?

**Comment by cbornhoft** [comment]
Yes, in the [v1.1 release](https://github.com/envms/fluentpdo/releases), a new method was added.

You can access the raw PDO instance by `$fpdo->getPdo()`

**Comment by novhex** [comment]
@cbornhoft : thank you for quick response sir actually why im asking for raw query because i integrate your ORM to my custom made framework and i get stuck with pagination. because im trying to write a code like this : "SELECT * from table LIMIT 0,5"  btw i'll check the docs for $fpdo->getPdo();

**Comment by cbornhoft** [comment]
With a simple query like that you should use the built-in functionality of Fluent.

You should be able to build your query above with `$fpdo->from('table')->limit('0, 5')`
