### ISSUE TITLE
Queries Doesn't work with column name having .(dot)

### ISSUE THREAD

**Issue by jasminder** [envms/fluentpdo#192]
I tried to insert into a table name having column name containing .(dot) .The query doesn't work . 
Example:
$j_values = array("new.m"=>"s");
$query_5 = $fpdo->insertInto("stats")->values($j_values);

**Comment by cbornhoft** [comment]
I don't think we'll ever be supporting dots in table names. They are used too extensively as a special character and should be avoided entirely.

If you *must* use them for a legacy system, escape the name using backticks. `new.m` becomes `\`new.m\``

**Comment by jasminder** [comment]
Thank You .
