### ISSUE TITLE
Update table row with its current value + new value

### ISSUE THREAD

**Issue by jasminder** [envms/fluentpdo#193]
Hey , 
How can i do this 
$values = array("last_printed"=>`last_printed` + 1);
$d = $fpdo->update("settings")->set($values)->execute();

The above query doesn't work . How to get this query to work.

**Comment by cbornhoft** [comment]
What is the error PHP and/or MySQL throws?

**Comment by jasminder** [comment]
Hey , 
Thank you . Got it sorted with FluentLiteral .

**Comment by jasminder** [comment]
Closing.
