### ISSUE TITLE
Multiple where clauses?

### ISSUE THREAD

**Issue by novhex** [envms/fluentpdo#196]
Hello may i ask if fluent PDO supports multple where clauses like
`$query = $fpdo->from('article')->where('id', 1)->where('title','foo')->where('date_published',date('Y-m-d'));`

and how do i do multiple where clauses like this

AND:
`WHERE field1=BLAH1 AND field2=BLAH2`
OR:
`WHERE field1=BLAH1 OR field2=BLAH2`

WHERE GROUP
`WHERE (field1=BLAH1 AND field2=BLAH2) AND (field4=BLAH4 AND field5=BLAH5)`

**Comment by leeoniya** [comment]
https://github.com/envms/fluentpdo/blob/master/tests/04-where-array.phpt

**Comment by novhex** [comment]
@leeoniya thanks leeoniya btw does the syntax work also with INSERT , UPDATE and DELETE queries?

**Comment by cbornhoft** [comment]
Yes, it works with all CRUD queries.

**Comment by PlanetGamingGG** [comment]
Hi, https://github.com/envms/fluentpdo/blob/master/tests/04-where-array.phpt shows Page Not Found.

**Comment by hapm** [comment]
The test refered to by the link can still be found [here](https://github.com/envms/fluentpdo/blob/v1.1.3/tests/04-where-array.phpt). For version 2.1.2 you find an updated test [here](https://github.com/envms/fluentpdo/blob/v2.1.2/tests/Queries/SelectTest.php#L80).
