### ISSUE TITLE
count($query) for grouped records returns wrong result

### ISSUE THREAD

**Issue by hapm** [envms/fluentpdo#199]
The current implementation of the Countable interface returns wrong results for grouped queries, as it simply replaces the select clause with `SELECT COUNT(*)`. It is even more complicated when you reuse defined column aliases in clauses like ORDER BY, HAVING or WHERE.

Instead of replacing the SELECT clause I suggest to wrap the hole query as a sub query and do a SELECT COUNT(*) on that:

`'SELECT COUNT(*) FROM ('.$query->getQuery().') AS thisWillBeHardToSelectBecauseItMustNeverBeASelectedTableAliasInAQueryEver'`

That is my current workaround query directly executed on the underlying pdo object.

**Comment by Jenselme** [comment]
Same problem here.

**Comment by cbornhoft** [comment]
@hapm do you have a full function/method you're currently using as a solution to this? And do you remove the `Countable` interface entirely in your fork?

I'm looking into the best approach to this now.

**Comment by cbornhoft** [comment]
So, we've looked into this and can't seem to reproduce it.

    $query = $fpdo->from('comment')->group('article_id');

produces the query

    SELECT comment.*
    FROM comment
    GROUP BY article_id

and if we run count on it, which utilizes the `Countable` interface

    $query->count();

it returns 2, as expected (3 total rows, 2 of which have the same `article_id`)

**Comment by hapm** [comment]
Because the first group has two records, try a better example. The resulting query would be 
```
SELECT COUNT(*) FROM comment GROUP BY article_id
```
This returns the count of records in the first group. If you have 2 comments for the first article, then sure, the result would be two as expected, but only because of coincidence.

**Comment by hapm** [comment]
Actually COUNT turns into a group aggregation and you get a record per group containing the number of records in that group. Then it returns only the value of the first record, what results in returning the number of comments on the first (or random, based on underlying implementation of group by) article.

**Comment by hapm** [comment]
The most elegant way to solve this would be to support nested queries, at least in the from clause. So we could use ->select("COUNT(*)")->from($SelectQueryObject). But implementing sort for subqueries opens up a big topic, that should be discussed in a different issue.

**Comment by cbornhoft** [comment]
Okay, nested queries are already a request. Closing this issue and I will add it as a reference there.

See issue #200
