### ISSUE TITLE
How to use cross join sql?

### ISSUE THREAD

**Issue by asnawisaharuddin** [envms/fluentpdo#206]
Saw in the file there's only two join method listed. Is there a way to use cross join ?

```
* @method SelectQuery  leftJoin(string $statement) add LEFT JOIN to query
 *                        ($statement can be 'table' name only or 'table:' means back reference)
 * @method SelectQuery  innerJoin(string $statement) add INNER JOIN to query
 *                        ($statement can be 'table' name only or 'table:' means back 
```

**Comment by cbornhoft** [comment]
Those are only two listed for IDE use and documentation purposes. You can use any join type the same way. Fluent uses the magic method `__call()` to build the query based on the method name. So in your instance, call it with `$fpdo->from("table")->crossJoin(...);

**Comment by asnawisaharuddin** [comment]
Hi, Thanks for the reply.

It still return an error when i'm using a cross join without specify on clause.

`->crossJoin("form_branch_quota");`

> Unknown column 'smbc_form.form_branch_quota_id' in 'on clause' 

But this will works

`->crossJoin("form_branch_quota ON 1=1")`
