### ISSUE TITLE
Adding $this->fromAlias . '.*' to every query should be optional

### ISSUE THREAD

**Issue by cdvrooman** [envms/fluentpdo#207]
I am using Postgres and when I execute queries that are grouped, I need to include all of the fields in the SELECT portion of the query in the GROUP BY clause. Fluent's habit of arbitrarily executing:
`$this->statements['SELECT'][] = $this->fromAlias . '.*';` (Line 55 of SelectQuery.php)
is problematic and should be optional IMHO.
My workaround was to disable that line altogether.

Also, from a query optimization standpoint, I should be able to return just 1 or two fields from a table with 100 fields instead of being forced to return all of them all of the time.

**Comment by hapm** [comment]
You can reset statements by passing `null`. I commonly used that: `$fdbo->from('mytable')->select(null)->select('someColumn')...`

**Comment by cbornhoft** [comment]
Yes, this is a very well-known annoyance, and one that currently does not have a catch-all solution. @hapm's workaround does the trick for now.

**Comment by cdvrooman** [comment]
Thanks for getting back so quickly. 
Yes, that would solve the issue. Thanks for the tip!
