### ISSUE TITLE
Move regex statements to their own class and methods

### ISSUE THREAD

**Issue by cbornhoft** [envms/fluentpdo#212]
For example, matching a table name and column using regex currently sits inside more than one method.

Instead of:

    preg_match_all('/.../', $subject, $matches);

the method could be:

    $matches = $regex->tableColumn($subject);

This makes the overall code DRYer, with improved readability.

**Comment by cbornhoft** [comment]
@StefanYohansson @maldoinc @sanabria91 thoughts?

**Comment by maldoinc** [comment]
Agreed, but I wouldn't call it regex or anything of that sort. What is uses to get the job done is irrelevant.

Also, it's best these should be unit tested with PHPUnit.

**Comment by cbornhoft** [comment]
Definitely doesn't have to be named regex, just the general idea that these matched patterns are located in one place rather than upon each case.
