### ISSUE TITLE
Weird memory bug

### ISSUE THREAD

**Issue by niklaswa** [envms/fluentpdo#221]
When I'm executing the following code:
```php
echo json_encode($inputData);
$qb = new FluentPDO($this->db);
$sql = $qb->insertInto('SURVIVAL.' . $table, $inputData);
echo 'Query: '.$sql->getQuery(true) . '<br>';
echo 'Parameters: '.json_encode($sql->getParameters());
return $sql->execute();
```

I get this output:
`{"VHOST_ID":"226","IP":"12","DNS":"12","IPADDRESS_TYPE_ID":"39","SERVICE_IP":"1","COMMENT":null}`

Query: `INSERT INTO SURVIVAL.IPADDRESS (VHOST_ID, IP, DNS, IPADDRESS_TYPE_ID, SERVICE_IP, COMMENT) VALUES (?, ?, ?, ?, ?, ?)`

Parameters: `["226","12","12","39","1",null]`

And here's the error. The script stops at this point.
`Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 140711718551584 bytes) in PATH/vendor/fpdo/fluentpdo/FluentPDO/InsertQuery.php on line 48`

The query get's perfectly executed and writes the values in the database.

What am I doing wrong here?

I'm on 1.1.2 with PHP Version 7.1.11 and using PDO with DB2.

**Comment by cbornhoft** [comment]
Hmm this is very odd, and something I have not run into. Everything looks fine from the data you've posted.

A few points/questions:

1. I recommend restarting `php-fpm` (or fcgi on apache) if you're running this through the web.
2. Does the script hang on `execute()` until running out of memory, or does this instantly happen?
3. It could have something to do with the null value not converting correctly to what DB2 requires, which could cause a memory leak in the PHP-DB2 driver. Have a look at [this question on SO](https://stackoverflow.com/questions/11692773/php-mysql-pdo-refuses-to-set-null-value) to see if maybe one of those null value conversions solves the problem.

**Comment by niklaswa** [comment]
1. Didn't help
2. Instantly
3. It happens without null values either

Another example:
```
{"VHOST_ID":173,"USER":"Test","TYPE_ID":2,"COMMENT":"Testing"}
Query: INSERT INTO SURVIVAL.USER_LIST (VHOST_ID, USER, TYPE_ID, COMMENT) VALUES (?, ?, ?, ?, ?)
Parameters: [173,"Test",2,"Testing"]
```

**Comment by cbornhoft** [comment]
The example in your last post, you have a parameter count mismatch. You're trying to insert 4 columns with 5 values.

**Comment by niklaswa** [comment]
Oh, sorry. I modified it to censor 2-3 fields. It was the right count. Sorry for the confusion.

**Comment by cbornhoft** [comment]
Have you tried using raw PDO and running the same queries? Looking at the error, it's on [line 48](https://github.com/envms/fluentpdo/blob/2bb54b27e6d53c35329ac7e651d869ac52f1944a/FluentPDO/InsertQuery.php#L48) which reads:

    return $this->getPDO()->lastInsertId($sequence);

All this is doing is attempting to get the last auto-increment (AI) value from the successful insert. It looks like you aren't using AI in your tables, that could possibly be the issue? It could also be an issue with DB2 support of `PDO::lastInsertId()`

**Comment by niklaswa** [comment]
I can not test it right now because I'm on vacation. But I can imagine that DB2 does not support this. Is it possible to execute the query without getting the last Insert ID?

**Comment by cbornhoft** [comment]
@niklaswa did you ever find a suitable solution to using DB2 with PDO? I'm curious if there is something I can implement in 2.0 to take this into account.

**Comment by niklaswa** [comment]
Yes, you can check the two commits on my fork: https://github.com/niklaswa/fluentpdo/commits/master
(Apperantly DB2 doesn't support it)
