### ISSUE TITLE
onDuplicateKeyUpdate

### ISSUE THREAD

**Issue by darkalchemy** [envms/fluentpdo#224]
I have been trying to use onDuplicateKeyUpdate with insertInto and I get this error:

```
Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number in vendor/lichtner/fluentpdo/FluentPDO/BaseQuery.php on line 151
```

Before, fluentpdo, I have always created the update portion as column = VALUES(column) but with fluentpdo, it must be an array, [column => $value].

What is the proper way to do this in fluentpdo?

Thank you

**Comment by cbornhoft** [comment]
Hey @darkalchemy, it looks like you're still using an older version of Fluent. Can you update to the latest stable release of the `envms/fluentpdo` repo?

Can you also post the exact php code you're writing and the resulting query?

**Comment by darkalchemy** [comment]
I have updated to dev-master. It appears that the composer structure has changed. Now this:
```
$fluent = new FluentPDO($pdo);
```
can't find the class. The readme stills shows it this way. What do I need to change to get it to load?

Thanks

**Comment by cbornhoft** [comment]
If you're using this with an existing app, it's best to use the `1.1.*` release until 2.0 is stable. The master branch is volatile.

**Comment by slideup-benni** [comment]
I have the same problem but i'm using the latest 1.1.* from composer.
