### ISSUE TITLE
how to show error when insert

### ISSUE THREAD

**Issue by tranchau1991** [envms/fluentpdo#225]
I am use fluentpdo and $debug= true, but not show error when insert,
how to get error when query?
thanks more.

**Comment by cbornhoft** [comment]
There are multiple ways to debug. Have a look at [`BaseQuery::debugger()`](https://github.com/envms/fluentpdo/blob/2bb54b27e6d53c35329ac7e651d869ac52f1944a/FluentPDO/BaseQuery.php#L166), which runs at the end of the query execution.

**Comment by tranchau1991** [comment]
Thank for answers but i am get null for error by example code blow... (i am using for class so some code can not correct)

$pdo = new PDO("mysql:dbname=" . DB_NAME, DB_USER, DB_PASS);
$this->dbconnect = new FluentPDO($pdo);
$this->dbconnect->debug = true;

$values = array(
	'user_id'=>$this->user_id,
	'background'=>'yellow',
	'permission'=>'public',
	'createdate' => date("Y-m-d H:i:s"),
	//'url' => '', //column ok
	'url123' => '', //column not exit
);
//$query = $this->dbconnect->insertInto('listnotes')->value($values)->execute();
$query = $this->dbconnect->insertInto('listnotes')->values($values);

$es=$query->execute();
$err=$query->debugger();

var_dump($err); //return null

**Comment by nomadme** [comment]
@tranchau1991 You can do something like this:

    $es=$query->execute();
    $err=$query->getResult();

You should uncomment  `else` in this [line](https://github.com/envms/fluentpdo/blame/a1616eb2bf0ecdac4689d6261be49c036d85c368/FluentPDO/BaseQuery.php#L151-L153) in `BaseQuery`.
