### ISSUE TITLE
column names not escaped correctly

### ISSUE THREAD

**Issue by slideup-benni** [envms/fluentpdo#226]
Hello,
in my database structure exists column names like "first" and "last". When i create an insert query it fails (without error) and the row wasn't added to the table.
I changed (quick and dirty) line 145 of lastQuery.php from
```
$columns = implode(', ', $this->columns);
```
to 
```
$columns = '`'.implode('`, `', $this->columns).'`';
```
and it works.
I dont know if this occurs other problems, but when not it would be very nice when you could fix this.
Thank you in advance

**Comment by cbornhoft** [comment]
Hey @slideup-benni, looks like what you're suggesting is a driver-specific fix. FluentPDO's philosophy is to support all RDBMS's that PDO itself supports. Only certain systems, like MySQL, support wrapping values in backticks, hence why we don't wrap them ourselves. The ideal solution to this is to avoid (if possible) naming tables and columns using potential SQL keywords.
