### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by dmitranoid** [envms/fluentpdo#227]
warning:
count(): Parameter must be an array or an object that implements Countable in /envms/fluentpdo/FluentPDO/BaseQuery.php on line 293 
centos7 PHP 7.2.0

**Comment by hapm** [comment]
Should be fixed by 9011a1df015b501a99fc3d110ce1f1c94f66eadf

**Comment by dmitranoid** [comment]
no fixes fox 1.* ?

**Comment by cbornhoft** [comment]
Yeah, I can likely add that part of the fix to the 1.* release as well. I apologize, I've been sick and busy over the holidays, haven't had time to do anything. Give me a few days and I will add that fix for 7.2 support.

Note that 1.* will never officially support PHP 7.2+ though.

**Comment by cbornhoft** [comment]
Fixed in #240
