### ISSUE TITLE
It is safe to use FluentLiteral (SQL injection)?

### ISSUE THREAD

**Issue by docloulou** [envms/fluentpdo#233]
Hi,
It is safe to use FluentLiteral or should I sanitize variable before ?

Thanks

**Comment by cbornhoft** [comment]
You should always sanitize your data. FluentLiteral does nothing to clean or sanitize, however, using PDO's prepared statements prevents the use of traditional SQL injection attacks.

**Comment by docloulou** [comment]
Thanks for your answer.
Prepared statement is already done for this kind of command ? :
$query = $fluent->insertInto('article',
        array(
            'user_id' => 1,
            'title' => '$_GET['title']'
        ));

Or I should clean the get variable too ?
