### ISSUE TITLE
How to Use BindParam ?

### ISSUE THREAD

**Issue by cmink-alone** [envms/fluentpdo#234]
$param = '%'.$keyword.'%';
$fpdo->from('data')->where('name LIKE :name')->fetchAll();

$fpdo->bindParam(':name', $param);

is it like that ?

**Comment by diogocavilha** [comment]
Hi.

Same doubt here.

I've been reading about FluentPDO in order to use it in my project and I've found nothing about bind params so far. That would be great. How can I do that?

**Comment by diogocavilha** [comment]
Anybody?

**Comment by cbornhoft** [comment]
The `where()` method takes a second param `$parameters`. You use this to bind named parameters automatically.

    $fluent->from('data')
        ->where('name = :name', [':name' => $param]);

**Comment by diogocavilha** [comment]
@cbornhoft thanks ever so much. 

I'll test it later.

**Comment by diogocavilha** [comment]
Hi @cbornhoft, is there a way to do this when inserting data?

Something almost like the where clause example, but for insert statement.

Sorry for asking too much, that's just because I can't find it in the docs.

**Comment by cmink-alone** [comment]
I use this : 

```
$param = '%'.$keyword.'%';
$fpdo->from('data')->where('(name LIKE ?)', $param)->fetchAll();
```

**Comment by diogocavilha** [comment]
@cmink-alone 

I'm not sure if get what you want, but doesn't the @cbornhoft example solve your problem?

```php
$fluent->from('data')
    ->where('name = :name', [':name' => $param]);
```

**Comment by cbornhoft** [comment]
Hey @diogocavilha, sorry I've been away.

I don't think that's possible with insert. Any particular reason you're looking for it?

If you take a look at [unit test #32](https://github.com/envms/fluentpdo/blob/legacy/tests/32-insert.phpt), you can see that the keys are what correlate to the column names, and in turn, it prepares the statement from the key/value array.

**Comment by diogocavilha** [comment]
Hi @cbornhoft, no problem.

So, I think that would be useful in order to do something like this...

```php
$stmt = $conn->prepare('INSERT INTO users (id, name) VALUES (:id, :name)');
$stmt->bindParam('id', $_POST['id'], PDO::PARAM_INT);
$stmt->bindParam('name', $_POST['name'], PDO::PARAM_STR);
$stmt->execute();
```
That's why I'm asking it.

**Comment by cbornhoft** [comment]
A prepared statement inherently protects against SQL injection. So:

    $conn->insertInto('users', [$_POST['id'], $_POST['name']);

will protect against injection just the same as your example above.

However, you should always clean your data beforehand. An attacker in your example could still easily inject javascript into your `$_POST['name']` and execute it later upon read.

**Comment by diogocavilha** [comment]
Hum, I see.

Thank you so much.
