### ISSUE TITLE
How to query scalar value?

### ISSUE THREAD

**Issue by Bogdaan** [envms/fluentpdo#235]
For example:
```
$totalTasksQuery = $qb->from('tests')
   ->select('count(tests.id) value')
   ->limit(1);
```

**Comment by cbornhoft** [comment]
Sorry, I'm not quite sure what you're asking, if you're still having this issue. Can you clarify?

**Comment by Bogdaan** [comment]
I mean fetch sclar value instead of array:
```php
$totalTasksQuery = $qb->from('tests')->limit(1); // <-- array
```

**Comment by cbornhoft** [comment]
Ah okay, no, you would have to convert it to a primitive type yourself.

It always returns in the form of an array or object since a table with one column is essentially pointless, and it's rare to only need one column of one row in a select.
