### ISSUE TITLE
Getting error on Base.php, Line 4 use Envms\FluentPDO\{Query,Literal,Structure,Utilities};

### ISSUE THREAD

**Issue by NJseo** [envms/fluentpdo#241]
Help with Base.php Line 4

use Envms\FluentPDO\{Query,Literal,Structure,Utilities};

arse error: syntax error, unexpected '{', expecting identifier (T_STRING) in /home/103614-78953.cloudwaysapps.com/mrdmprgqyc/public_html/connections/fluentpdo/src/Queries/Base.php on line 4
--

1 | 0.0002 | 248016 | {main}( ) | ../index.php:0
2 | 0.0004 | 260920 | include( '/home/103614-78953.cloudwaysapps.com/mrdmprgqyc/public_html/connections/fluentpdo/FluentPDO.php' ) | ../index.php:1

**Comment by cbornhoft** [comment]
It looks like you're trying to use the 2.0 branch with PHP 5.x

Fluent 2.0 only supports PHP 7+. If you have to use PHP 5, make sure to follow the instructions in the readme to use the legacy 1.1.x versions.

**Comment by NJseo** [comment]
Thank you

**Comment by NJseo** [comment]
Its never just simple. I removed the files and reinstalled and now its coming back as:
[master_nndxrbvnxz]:fluentPDO$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
                                                                                                                                                                                              
  Problem 1                                                                                                                                                                                   
    - The requested package envms/fluentpdo No version set (parsed as 1.0.0) is satisfiable by envms/fluentpdo[No version set (parsed as 1.0.0)] but these conflict with your requirements or 
minimum-stability.

**Comment by cbornhoft** [comment]
This is a composer error. It means you aren't supplying a version so it's trying to pull 1.0, which is not an official release of Fluent.

Provide a version:

    "require": {"envms/fluentpdo", "^1.1.0"}
