### ISSUE TITLE
Date Format problem

### ISSUE THREAD

**Issue by PandaTamara** [envms/fluentpdo#243]
Hi! Calling DATE_FORMAT function in query make broke all works. If i use:

`->select('DATE_FORMAT(t.ticket_get_date, "%d-%m-%Y") as tdate);`

all fine, but if i use dots

`->select('DATE_FORMAT(t.ticket_get_date, "%d.%m.%Y") as tdate);` 

i get error. Check these, please

**Comment by cbornhoft** [comment]
Thanks! We're already aware of this and are looking into ways to fix it in the upcoming version.

**Comment by krahamath** [comment]
Add to milestone with label because you have chance to forget.
