### ISSUE TITLE
Check prepare result before using it

### ISSUE THREAD

**Issue by element-code** [envms/fluentpdo#244]
Hi, 
im getting a `Call to a member function setFetchMode() on boolean` exception when calling `fetchAll()`.
It turns out, that in [`BaseQuery::execute()` line 130](https://github.com/envms/fluentpdo/blob/7d31e9b9028466ec41b0a0760b1491b091bcf8e8/FluentPDO/BaseQuery.php#L130) the `$result` never gets checked if it's `false` (table does not exist or other errors), before using it.

Please discuss if it makes sense to do a check here and let me know, i will do a pull request then - if youre intrested in.

**Comment by cbornhoft** [comment]
Thanks @element-code. Feel free to make a PR for the legacy version 1.1.x and I will merge and release.

For 2.0, too much is being re-written to take this into account right now.

**Comment by cbornhoft** [comment]
Fixed in 2.0
