### ISSUE TITLE
Always getting "SQLSTATE[08004] [1040] Too many connections" and "Fatal error:  Call to a member function from()"

### ISSUE THREAD

**Issue by krahamath** [envms/fluentpdo#246]
I am getting always Errors are following:
"`SQLSTATE[08004] [1040] Too many connections`" 
AND
 "`Fatal error:  Call to a member function from() on null`"

HERE IS CODE:
```
function db() {
	$host       = "localhost";
	$username   = "root";
	$password   = "";
	$dbname     = "databasename";
	$dsn        = "mysql:host=$host;dbname=$dbname";
	$options    = array(
			PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
	                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
	            );
	try {
		$pdo = new PDO($dsn, $username, $password, $options);
		$fluent = new FluentPDO($pdo);
		return $fluent;
	} catch(PDOException $exception) {
        echo $exception->getMessage();
    }
}
$query = db()->from('product')->where(array('id' => '12', 'locale' => 'en_US'))->fetch('name');
```

**Comment by cbornhoft** [comment]
If you're getting the server error "Too many connections", that means your SQL server is refusing your request. If Fluent does not receive a valid connection, it will not work.

**Comment by krahamath** [comment]
I am using two db connections in localhost, is this cause the problem?
```
function db() {
..... local db
}

function db2() {
..... remote db
}
```

**Comment by cbornhoft** [comment]
Possibly if your local server has a connection limit of 1. Have a look at the MySQL [max_connections](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_connections) variable documentation

**Comment by krahamath** [comment]
Previously i used to connect mysqli it works now i wanted to upgrade with pdo and some problem happening in server also(OVH hosting)

**Comment by krahamath** [comment]
I am sure connection is not an issue. Something wrong.. very refresh error showing on random file and random line.

**Comment by krahamath** [comment]
no solution to this?

**Comment by cbornhoft** [comment]
See #247. This has nothing to do with FluentPDO
