### ISSUE TITLE
SQLSTATE[08004] [1040] Too many connections - its dead?

### ISSUE THREAD

**Issue by krahamath** [envms/fluentpdo#247]
I am getting always Errors are following:
"`SQLSTATE[08004] [1040] Too many connections`" 
AND
 "`Fatal error:  Call to a member function from() on null`"

Re-writing again because no reply for previous. Let me know please is the project is dead ?

**Comment by azurre** [comment]
This problem on your side. You should to increase max_connections in your SQL server settings.

**Comment by krahamath** [comment]
Check #246 I used mysqli connection previously it worked without any changes.

**Comment by azurre** [comment]
You can also try to count of connections (add logging where you create new connection). Probably you have some loop and you create a lot of connections.
99.9% that this is logic(or environment) issue on your side.

**Comment by cbornhoft** [comment]
No this project is not dead, and this is not a FluentPDO issue. Fluent does not handle or manage connections, this is not an issue with Fluent. The sole purpose of the `close()` method is to ensure the PDO connection instance Fluent was given is closed, so a new connection can be made the next time.
