### ISSUE TITLE
Does anyone else need the LIKE query?

### ISSUE THREAD

**Issue by huangyuzhen** [envms/fluentpdo#250]
sql statement like this:

    select * from users where name like 'm%'

**Comment by jkufner** [comment]
Yes. Another usecase for such a query is to request subtree when tree structure is stored using paths in a varchar column, e.g., `... LIKE CONCAT(:path, "%")`, where `:path` is `"/a/b/"`.

**Comment by cbornhoft** [comment]
What seems to be the issue here? You can build a query:

    $fluent->from('users')
        ->where("name LIKE '?'", 'm%');

That should build the exact query you're looking for.

**Comment by cbornhoft** [comment]
Closing as solved
