### ISSUE TITLE
Issue with UPDATE statement

### ISSUE THREAD

**Issue by karneaud** [envms/fluentpdo#259]
I'm using the following method to update records

```
$sent_attendees = array_keys($this->attendees);
    $sent_attendees = array_diff($sent_attendees, $this->failed);
    $this
      ->db
        ->debug = true;
      $this
        ->db
        ->update(DB_TABLE)
        ->set('sent_at', new \FluentLiteral('NOW()'))
        ->where('email', $sent_attendees)
        ->execute();
```

When I get the following when debugging `$sent_attendees` and the `$this->db-debug=true`

> 01T03:45:19.401965355Z > There is 1 output:
> 01T03:45:19.402059677Z => In tests\units\src\EmailAttendees::testSuccessfulBatchEmails():
> 01T03:45:19.402117697Z Array
> 01T03:45:19.402159207Z (
> 01T03:45:19.402199988Z     [0] => turpis.egestas.Aliquam@aliquetvel.co.uk
> 01T03:45:19.402248894Z     [1] => elit.dictum.eu@ultriciesornare.net
> 01T03:45:19.402299414Z     [2] => luctus.Curabitur@magnaDuis.org
> 01T03:45:19.402342591Z     [3] => Suspendisse.commodo@nequeMorbi.net
> 01T03:45:19.402384622Z     [4] => aliquam.eu.accumsan@risus.edu
> 01T03:45:19.402426601Z )
> 01T03:45:19.402466600Z # /srv/src/src/EmailAttendees.php:107 (0.000 ms; rows = 0)
> 01T03:45:19.402594412Z UPDATE email_attendees
> 01T03:45:19.402638265Z     LEFT JOIN turpis ON turpis.id = email_attendees.turpis_id
> 01T03:45:19.402680505Z     LEFT JOIN egestas ON egestas.id = turpis.egestas_id
> 01T03:45:19.402722119Z     LEFT JOIN Aliquam ON Aliquam.id = egestas.Aliquam_id
> 01T03:45:19.402763368Z     LEFT JOIN elit ON elit.id = email_attendees.elit_id
> 01T03:45:19.402804670Z     LEFT JOIN dictum ON dictum.id = elit.dictum_id
> 01T03:45:19.402845920Z     LEFT JOIN eu ON eu.id = dictum.eu_id
> 01T03:45:19.402886388Z     LEFT JOIN luctus ON luctus.id = email_attendees.luctus_id
> 01T03:45:19.402928263Z     LEFT JOIN Curabitur ON Curabitur.id = luctus.Curabitur_id
> 01T03:45:19.402969825Z     LEFT JOIN Suspendisse ON Suspendisse.id = email_attendees.Suspendisse_id
> 01T03:45:19.403066439Z     LEFT JOIN commodo ON commodo.id = Suspendisse.commodo_id
> 01T03:45:19.403122063Z     LEFT JOIN aliquam ON aliquam.id = email_attendees.aliquam_id
> 01T03:45:19.403164511Z     LEFT JOIN accumsan ON accumsan.id = eu.accumsan_id
> 01T03:45:19.403205969Z     LEFT JOIN co ON co.id = email_attendees.co_id
> 01T03:45:19.403246802Z SET sent_at = NOW()
> 01T03:45:19.403287635Z WHERE email IN co.uk', eu@ultriciesornare.net', Curabitur@magnaDuis.org', commodo@nequeMorbi.net', accumsan@risus.edu')

I'm using PHP 7.0.x with FluentPDO version 1.1.*

Should I try the alphas?

**Comment by cbornhoft** [comment]
Hey @karneaud go ahead and try the alphas to see if it still occurs. alpha5 passed all tests.

Also, can you tell me what values your variables contain? Hard to match up the debug output with the query above.

**Comment by karneaud** [comment]
@cbornhoft  I myself as I did not do any `LEFT JOIN` in my logic I was simply trying to update records where `email` was in the following array

```
Array
 (
 [0] => turpis.egestas.Aliquam@aliquetvel.co.uk
[1] => elit.dictum.eu@ultriciesornare.net
[2] => luctus.Curabitur@magnaDuis.org
[3] => Suspendisse.commodo@nequeMorbi.net
[4] => aliquam.eu.accumsan@risus.edu
 )
``

I was hoping you had some insights as there is no `LEFT JOIN turpis ON turpis.id = email_attendees.turpis_id`

**Comment by cbornhoft** [comment]
Ah yes, this is a known bug that we're currently in the middle of fixing right now. Essentially if `$parameters` contains any dots `.`, the smart join system will kick in and think you're trying to join a table. The way to fix this right now is to call:

    $query = $this->db->update(DB_TABLE)
        ->set('sent_at', new \FluentLiteral('NOW()'))
        ->where('email', $sent_attendees);
    $query->disableSmartJoin()
        ->execute();

**Comment by cbornhoft** [comment]
Alight, the latest alpha contains a way to prevent the automatic joins without disabling them entirely. You have a couple of options here:

1) The newly added way:

    $i = 0;
    foreach ($sent_attendees as $email) {
        str_replace('.', '\.', $sent_attendees[$i++];
    }

    // query stays the same
    $this
        ->db
        ->update(DB_TABLE)
        ->set('sent_at', new \FluentLiteral('NOW()'))
        ->where('email', $sent_attendees)
        ->execute();

2) New way since alpha4

    $this
        ->db
        ->update(DB_TABLE)
        ->set('sent_at', new \FluentLiteral('NOW()'))
        ->where('email IN (?,?,?,?,?)', $sent_attendees)
        ->execute();

The second way is better since it uses prepared statements, however if you have an unknown amount of emails, then you'd likely need to count the number of params to pass beforehand.

**Comment by cbornhoft** [comment]
Closing as solved
