### ISSUE TITLE
Is there a mistake in readme file?

### ISSUE THREAD

**Issue by tupianku** [envms/fluentpdo#268]
I've upload 2.1 release source code to dir Envms/FluentPDO/src/ 
then require the file Query.php

require "Envms/FluentPDO/src/Query.php";

When I create a new PDO instance, and pass the instance to FluentPDO:

 $pdo = new PDO("mysql:dbname=fluentdb", "root");
 $fluent = new FluentPDO($pdo);

 I got this error message:
 Fatal error: Uncaught Error: Class 'FluentPDO' not found

I am sure I require Query.php file with the correct path, but I got the mistake all the time. what's wrong?

**Comment by cbornhoft** [comment]
Read me was updated last week
