### ISSUE TITLE
Memory increasing for select in a loop

### ISSUE THREAD

**Issue by rodmar35** [envms/fluentpdo#273]
Hello,

I'm using fluentpdo V2.1.1 with slim 3.
In a batch with loop (around 38 000), a need select query to get one id.

CODE V1 : WITH FLUENTPDO
------
```
$pdo = new \PDO('mysql:host=localhost;dbname=xxx;charset=utf8', 'root', '');
$resquery = null;
$fpdo = new Query($pdo);
$fpdo->debug = false;
    for( $i= 0 ; $i <= 100 ; $i++ ) {
        for( $o= 0 ; $o <= 380 ; $o++ ) {
            $query = $fpdo->from('games')->where('external_id = ?', $o);
            $resquery = $query->fetch(); 
        }
     dump(memory_get_usage());
    }
```

Memory used in First call : 11MB 
**Memory used in Last call : 1GB** 

CODE V2 : WITH PDO ALONE
------
```
$pdo = new \PDO('mysql:host=localhost;dbname=xxx;charset=utf8', 'root', '');
$pdo->setAttribute(\PDO::ATTR_DEFAULT_FETCH_MODE, \PDO::FETCH_BOTH);
$resquery = null;

    for( $i= 0 ; $i <= 100 ; $i++ ) {
        for( $o= 0 ; $o <= 380 ; $o++ ) {
            $query = $pdo->query('SELECT * FROM games WHERE external_id = $o');
            $resquery = $query->fetch(); 
        }
     dump(memory_get_usage());
    }
```
Memory used in First call : 1,11MB 
Memory used in Last call : 1,21MB 

-----
Why there is a big difference in memory used between fluentpdo (1GB) and simple pdo query (1Mo) ?
Is it possible to clear a fluentpdo result ?
Thanks in advance
Rodmar

**Comment by cbornhoft** [comment]
I haven't looked into this yet, but my guess at first glance is because every `FluentPDO\Query` method call creates a new instance of a `Select`, `Insert`, `Update`, or `Delete`. The garbage collection would never have a chance to run since this is inside 1 script, hence the memory consumption.

Can I ask why you're running your queries like this? It's an extremely inefficient way doing a select when you could simply use a `BETWEEN` statement.

**Comment by rodmar35** [comment]
thanks for your feedback. My previous code was simplified to show you the memory behavior.  I'm handling soccers datas from json file and I'm trying to do a mass import with it.  I have about 100 json files and in each there are 380 games. And in each match have event information like players, goals, substitution,.. In json file, Every games and events have an id. In my DB i'v got multiple table with my own primary key id and i store the id from json as unique. Then during import, i check id and json event id and create/select according presence.

For resume : 

```
$pdo = new \PDO('mysql:host=localhost;dbname=xxx;charset=utf8', 'root', '');
$resquery = null;
$fpdo = new Query($pdo);

$files = glob("folder/*.json");

// loop each json file in folder
foreach($files as $json_file){

    $handle = fopen($json_file, "r");

    // get json content
    if (filesize($json_file) > 0) {

        $contents = fread($handle, filesize($json_file));
        $obj = json_decode($contents, true);

	// For each game in json file
        foreach ($obj['matches'] as $game) {

            $games_id = $game["id"];
            $home_team_id = $game["hometeamid];
            $away_team_id = $game["awayteamid];
            //...

            // check if game already exist in db
            $querygame = $fpdo->from('games')->where('jsonid = ?', $games_id);
            $checkgame = $querygame->fetch();

            // if match doesn't alredy exist
            if (!checkgame) {

            $queryhometeam = $fpdo->from('teams')->where('jsonid = ?', $home_team_id);
            $checkhometeam = $queryhometeam->fetch();

            // if hometeam doesn't already exist
            if (!checkhometeam) {

                 $values = array(
                      'jsonid' => $game["hometeamid], 
                      'label' => $game["hometeamname]
                 );

		$query = $this->fpdo->insertInto('teams')
		    ->values($values)
		    ->ignore()
		    ->execute();
        	 }

        	// for each player in home team 
        	foreach ($game['player'] as $player) {

        	    // query to ckeck if player exist already in db
        	    // if true get id
        	    // if false, create it and get lastinsertid
        	}

        	// repeat code for away team...

        } else {

        	// Game exist already
        	// query update onDuplicateKey datas like score, goal, player ....
        }
    }
    fclose($handle);
}
```

I understand this isn't necessarily due to FluentPdo.
Thanks in advance
RodMar

**Comment by cbornhoft** [comment]
Calling the garbage collector mid-script shouldn't have an impact on anything but data that has been used up already, so you should be okay. Glad you got it sorted!
