### ISSUE TITLE
If the table has no primary key with sequence (auto-increment) insert method will throw an error

### ISSUE THREAD

**Issue by roquie** [envms/fluentpdo#274]
How to reproduce?

1. create a PostgreSQL table without sequence
2. insert row using Fluentpdo.
3. Catch the following error:

```bash
PDOException: SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval is not yet defined in this session
```

It's a bug.

Solution without breaking changes:

```php
// In Insert.php

public function execute($sequence = null, $lastInsertId = true)
{
     $result = parent::execute();
     if ($result && $lastInsertId) {
        return $this->fluent->getPdo()->lastInsertId($sequence);
     }

     return false;
}
```

**Comment by roquie** [comment]
Or create other method, like that:
```php
<?php
public function cleanExecute() // or call it `produce()`
{
     return parent::execute();
}
```

It more readable solution.

**Comment by cbornhoft** [comment]
Thanks for reporting this. It is rare for a table to have no primary key but it certainly does happen. I should be able to release a fix for this today.

**Comment by cbornhoft** [comment]
Released in [v2.1.2](https://github.com/envms/fluentpdo/releases/tag/v2.1.2)

**Comment by roquie** [comment]
Thanks! But I have two comments for better code :)
https://github.com/envms/fluentpdo/commit/3af5c02ec3d38654e0346029ccbcd8aca930a663

**Comment by cbornhoft** [comment]
Alright I will take those into consideration the next release, thanks!
