### ISSUE TITLE
Class 'Envms\FluendPDO\Query' not found

### ISSUE THREAD

**Issue by flanderboy** [envms/fluentpdo#281]
Hello,
I install FluentPDO is via composer but I receive this error:

`Class 'Envms\FluendPDO\Query' not found`

`$fpdo 			= new \Envms\FluendPDO\Query($this->db);`

my php version is

`PHP 7.2.4 on ubuntu16.04.1`

**Comment by SandroMaglione** [comment]
I had this error too. I noticed that the readme has a typo.
It is not _FluendPDO_ but _FluentPDO_. 

`$fpdo = new \Envms\FluentPDO\Query($this->db);`

**Comment by Jazz-Man** [comment]
#284

**Comment by cbornhoft** [comment]
Apologies for the delay, this is now fixed.
