### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by darkalchemy** [envms/fluentpdo#307]
I just upgraded to version 2.2.0 and what worked in 2.1.2 no longer does. What is the correct way to get the debug output?

This worked in 2.1.2 but errors now with undefined method debug();. Other than setting $debug to false and changing the method name from debugger to debug, I don't see any other changes that would break this bit of code.

```
$fluent->debug = function ($BaseQuery) {
...
}
```

I would appreciate any insight you could give me.

Thank you

**Comment by kaerusdev** [comment]
In file Queries/Base.php on the line 579 replace

`$this->fluent->debug($this);`

to 

`call_user_func($this->fluent->debug, $this);`

**Comment by darkalchemy** [comment]
Thanks for the reply. But isn't there any way to this without modifying this code?

**Comment by darkalchemy** [comment]
@kaerusdev This does work now in the same way as before. For that, many thanks,

I do use this in a couple of projects so modifying this code, short of creating and publishing a fork, is not really the direction that I would like to go.

Can anyone direct me in the right direction here?

**Comment by darkalchemy** [comment]
It seems it was changed cbafbca with no reason attached.

**Comment by darkalchemy** [comment]
Ok. So using my own repo is my only choice then.

**Comment by cbornhoft** [comment]
@darkalchemy I'm sorry, I'm looking into why I'm intermittently getting notifications of issues here.

By assigning `debug` to a function/method like you did, you should be able to simply call that later. Changing the line to `$this->fluent->debug($this);` was purely to simplify the call. Would you be able to share the code block you have so I can test some use cases?

**Comment by darkalchemy** [comment]
@cbornhoft 
When I use it without modifying it, it echoes immediately to the page instead of returning the content. With the code reverted to how it was previously, it returns the content as expected. 


I will post a snippet when I get home tonight. 

Thanks

**Comment by cbornhoft** [comment]
Great thanks! I'll take a look as soon as you're able to send it.

**Comment by darkalchemy** [comment]
This is the full code of what I'm using.
`    $fluent->debug = function ($BaseQuery) {
        global $container;

        $params = [];
        $query = str_replace([
            ' ?',
            '(?',
        ], [
            ' %s',
            '(%s',
        ], $BaseQuery->getQuery(true));
        $paramaters = $BaseQuery->getParameters();
        $time = $BaseQuery->getExecutionTime();
        if (!empty($paramaters) && count($paramaters) >= 1) {
            foreach ($paramaters as $param) {
                if (is_int($param)) {
                    $params[] = $param;
                } else {
                    $pdo = $container->get(PDO::class);
                    $params[] = $pdo->quote($param);
                }
            }
            $query = vsprintf($query, $params) . "\n";
        }

        if (!empty($query)) {
            store_query(trim($query), $time, $params);
        }
    };
`

This code stores the content in temp cache so that it can be displayed later on the page.

I appreciate you looking into it for me @cbornhoft.

**Comment by cbornhoft** [comment]
I haven't forgot about this, I have a new docker environment built for this and testing with it now. Will have a fix in the next few days!

**Comment by cbornhoft** [comment]
Okay take a look at the latest release and see if it fixes your issue @darkalchemy. Appreciate the patience while I got things sorted!

https://github.com/envms/fluentpdo/releases/tag/v2.2.1

You can now declare `debug` as a Closure or anonymous function

**Comment by darkalchemy** [comment]
The update works without issue.

Thanks @cbornhoft I appreciate you taking the time to look into it.
