### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by levacic** [envms/fluentpdo#311]
I couldn't find any issues mentioning this so opening a new one.

The [current README mentions](https://github.com/envms/fluentpdo/blob/90048d9ae637278ccde922f197b11483df3a48ea/readme.md#version-2x):

> #### Version 2.x
>
> The stable release of FluentPDO and actively maintained. Officially supports PHP 7.3 to PHP 8.0,
but it can work with previous versions of PHP 7.

However, this apparently does not actually include PHP 8.0, as the [current `composer.json`](https://github.com/envms/fluentpdo/blob/90048d9ae637278ccde922f197b11483df3a48ea/composer.json#L19) has this constraint:

```json
"php": "^7.1"
```

Thus, it's not possible to actually install this package in a PHP 8.0 environment (unless Composer is told to ignore platform requirements, which is bad practice).

Furthermore, the [`.travis.yml`](https://github.com/envms/fluentpdo/blob/90048d9ae637278ccde922f197b11483df3a48ea/.travis.yml#L2-L5) file is configured so as not to test the code on PHP 8.0.

Are there any plans to make Version 2.x compatible with PHP 8.0? Thanks!

**Comment by cbornhoft** [comment]
Hey @levacic, good catch, thanks!

I'll update the constraints to include both 7 and 8. I have tested PHP 8 within my development environment, so I do know it works there. Updating Travis could be quick and easy, or a pain depending on what else they changed along with 8.

**Comment by levacic** [comment]
Hi @cbornhoft, do you need any help with this, in the form of a PR or something? If so, what would you like changed except for the `composer.json` constraint (where I'd suggest just replacing `^7.1` with `^7.1|^8.0`).

I've checked the other dependencies of this package (there's only two dev dependencies, so not much to check anyway):

- The latest `phpunit/phpunit:^8.0` is compatible with PHP 8, so unit tests should run fine
- `envms/fluent-test:^1.0` has no platform constraints (or any other for that matter), and the code is simple enough that it obviously doesn't have compatibility issues

I haven't used Travis in a long time, so I'm not sure if just adding PHP 8.0 to `.travis.yml` should do the trick?

Note that I didn't actually do any PHP 8 compatibility testing for this package, I'm just assuming that it works correctly based on your comment.

Thanks for the help!

**Comment by cbornhoft** [comment]
Absolutely, help is always welcome! Feel free to make a PR with the changes, and Travis should pick it up to test.

If you aren't able to figure it out, I _should_ have some time early next week to take a look. Work has been busier than anticipated right now.
