### ISSUE TITLE
The select examples don't work

### ISSUE THREAD

**Issue by fernandorotermund** [envms/fluentpdo#314]
The select examples don't work because the "**->fetchAll()**" method is missing.

The example looks like this:
$query = $fluent->from('comment')->where('article.published_at > ?', $date)->orderBy('published_at DESC')->limit(5);

But it should go like this:
$query = $fluent->from('comment')->where('article.published_at > ?', $date)->orderBy('published_at DESC')->limit(5)->fetchAll();

**Comment by cbornhoft** [comment]
@fernandorotermund good catch, I've fixed it now!
