### ISSUE TITLE
The ->fetchAll() can be used to put the result in a variable?

### ISSUE THREAD

**Issue by fernandorotermund** [envms/fluentpdo#315]
The ->fetchAll() can be used to put the result in a variable?

I'm using Fluentpdo to build my models, can I use it like this?

```
class Customers {

    public $fluent;

    public function __construct()
    {

        $pdo = new PDO('mysql:host='. DB_HOST .';port='. DB_PORT .';dbname='. DB_DATABASE, DB_USERNAME, DB_PASSWORD, [PDO::ATTR_PERSISTENT => false]);
        $this->fluent = new \Envms\FluentPDO\Query($pdo);
        
    }

    public function select() 
    {

        return $this->fluent->from('customers');
    
    }


}

$teste = new Customers();
$result = $teste->select()->limit(10)->fetchAll();
```

**Comment by cbornhoft** [comment]
Hey @fernandorotermund,

Fluent can definitely be used the way you have it now.

Another alternative is to pass your model class name to Fluent, and PDO can populate the model for you:

    class Customers {...}

    $customer = $fluent->asObject('Customers')->from('customers')->fetch();

A new instance of your `Customers` model will be created and saved to `$customer`.
