### ISSUE TITLE
Running manual queries

### ISSUE THREAD

**Issue by sifro** [envms/fluentpdo#51]
HI,

I have some complex SQL queries that I couldn't replicate with FluentPDO. Is it possibile to run a query "manually" by enterint the raw SQL?

EDIT: in the meanwhile, i've found a way to select only a few columns thanks to an issue here on git and i've managed to create my query.

An additional question though: how can I debug queries? On SELECTs, I'm using 

var_dump($query->execute());

..but is there a better way (that for example doesn't execute the query in INSERT\UPDATE\DELETE statements)?

**Comment by GelaniNijraj** [comment]
Is there a way to execute a raw query?
