### ISSUE TITLE
Select only specific fields

### ISSUE THREAD

**Issue by sharique** [envms/fluentpdo#57]
I'm executing following query to select specific fields from table, but it is returning all fields.

`$query = $this->fpdo->from('table2')->where('someid', $someid)->select('field1');`

**Comment by TCB13** [comment]
@lichtner please change this behavior with you get some time. This is kinda annoying. Thank you ;)

**Comment by BeOleg** [comment]
+1, would you accept a contribution?

**Comment by TCB13** [comment]
@BeOleg just check this: https://github.com/usmanhalalit/pixie
