### ISSUE TITLE
LIKE statement with integer

### ISSUE THREAD

**Issue by bee-interactive** [envms/fluentpdo#71]
Hi!

I want to execute a query with a LIKE %% Statement and it works well when the terms are letters and words but when I try with just a number like a year, nothing is returned. Could someone help me to achieve this query?

Here are my query:

$query = $fpdo->from('table')->where('keywords LIKE ?', "%$terms%")->fetchAll();

Thanks!

**Comment by markslone** [comment]
This is not working for me. It is just showing up blank not fetching any results
