### ISSUE TITLE
Increment or de-increment value

### ISSUE THREAD

**Issue by bee-interactive** [envms/fluentpdo#80]
Hi!

I'm trying to achieve this with fluentpdo: 

UPDATE product SET stock = stock - 1 WHERE id = 5;

I've tried some ideas but none worked yet.. Could you help me? Thanks a lot!

Queries tried so far:

$query = $fpdo->update('products')->set(array('stock' => -1))->where('id', 5)->execute();
$query = $fpdo->update('products')->set(array('stock' => '- 1'))->where('id', 5)->execute();
$query = $fpdo->update('products')->set(array('stock' => 'stock - 1'))->where('id', 5)->execute();

**Comment by Lefthandmedia** [comment]
is there a solution for this allready?

**Comment by beeInteractive** [comment]
Hi!

This is working for me:

$id = 5;
$field = 'stock';
$amount = 1;

$increment = array($field => new FluentLiteral($field.' + '.$amount));

$fpdo->update('products')->set($increment)->where('id', $id)->execute();
